### ISSUE TITLE
How to work with your package

### ISSUE THREAD

**Issue by designloud** [oldtimeguitarguy/plaid#3]
Hi, I have am using your package but having some trouble getting up and going and can't seem to find any documentation or help besides this:

I am using the javascript from the Plaid API documentation so the user picks their back and enters their credentials.  Then I receive a public token which I pass to a PlaidController where I am trying to implement your package to exchange it for an access token and check balance.

I get as far as getting a public token and sending it to my controller, but using your package I am not sure how I exchange that for an access token or get the balance, etc.

Here is what the Plaid API documentation gave me for the pop up to select back and enter credentials:
```
`<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script type="text/javascript">
var handler = Plaid.create({
  clientName: 'Plaid Walkthrough Demo',
  env: 'sandbox',
  key: 'abc12345667890', // Replace with your public_key to test with live credentials
  product: ['auth', 'transactions'],
  //webhook: '[WEBHOOK_URL]', // Optional – use webhooks to get transaction and error updates
  selectAccount: false, // Optional – trigger the Select Account
  onLoad: function() {
    // Optional, called when Link loads
  },
  onSuccess: function(public_token, metadata) {
    // Send the public_token to your app server.
    // The metadata object contains info about the institution the
    // user selected and the account ID, if `selectAccount` is enabled.
    $.post('/get_access_token', {
      _token: $('meta[name=csrf-token]').attr('content'),
      public_token: public_token,
    });

    console.log(public_token);
    console.log(metadata);
  },
  onExit: function(err, metadata) {
    // The user exited the Link flow.
    if (err != null) {
      // The user encountered a Plaid API error prior to exiting.
    }
    // metadata contains information about the institution
    // that the user selected and the most recent API request IDs.
    // Storing this information can be helpful for support.
  }
});

$('#link-button').on('click', function(e) {
  handler.open();
  // Alternatively, you can have a specific institution
  // prompt for authentication. Example:
  //
  // handler.open('ins_100000');
  //
  // This will open Link with Union Bank as the institution.
});
</script>`
```

Once I do that I receive a public token in my PlaidController but how do I interact with their API and exchange this for an access token using your package?

**Comment by karlhepler** [comment]
Yeah - Sorry my documentation isn't complete yet. I recently replied to another person with the following answer: https://github.com/oldtimeguitarguy/plaid/issues/1#issuecomment-266752990

Please take a look at that - hopefully it can point you in the right direction. Based on what I'm seeing here, it looks like you're using JS to get the token from the API, then you aim to use that token to make requests via your PHP server.

I'm not too familiar with what the JS API returns, but assuming that this "public token" is the same thing as the "access token" required with each PHP request, I would say you need to just post that to your server after you receive it from Plaid. When the server grabs it, you need to throw it into a class that implements `OldTimeGuitarGuy\Plaid\Contracts\User`. Then you just pass an instance of that class into each request type you need to perform.

Take a look at the link - I have a pretty good example there.
